services:
  time-ui:
    build:
      context: .
      target: development
      args:
        - USER_ID=1000
    container_name: time-lab
    # ESTO ES LO QUE ARREGLA EL PROBLEMA EN UBUNTU
    # network_mode: "host" 
    user: "time"
    volumes:
      - .:/app
      - time_node_modules:/app/node_modules
    # La sección 'ports' se elimina o se comenta porque ya no es necesaria
    ports:
      - "5188:5188"
    environment:
      - NODE_ENV=development
    restart: unless-stopped

volumes:
  time_node_modules:
